# Generated by Django 2.1.7 on 2019-04-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
