# Generated by Django 2.1.7 on 2019-05-02 17:47

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=home.models.upload_image_path)),
                ('ytlink', models.CharField(max_length=100, unique=True)),
                ('fblink', models.CharField(max_length=100, unique=True)),
                ('instalink', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
