# Generated by Django 2.1.7 on 2019-05-02 17:57

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=home.models.upload_image_path)),
                ('message', models.CharField(max_length=100, unique=True)),
                ('customername', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
