# Generated by Django 2.1.7 on 2019-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='customername',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
