# Generated by Django 2.1.7 on 2019-05-02 18:45

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190502_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=home.models.upload_image_path)),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
