# Generated by Django 2.1.7 on 2019-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_enquiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
