# Generated by Django 2.1.7 on 2019-05-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190503_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiries',
        ),
    ]
