# Generated by Django 2.1.7 on 2019-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190503_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiries',
            name='date',
            field=models.DateField(default='2019-06-23', unique=True),
            preserve_default=False,
        ),
    ]
