# Generated by Django 2.1.7 on 2019-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_enquiries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10, unique=True)),
                ('lastname', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=10, unique=True)),
                ('phoneno', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
