# Generated by Django 2.1.7 on 2019-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_enquiries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='firstname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='lastname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
