# Generated by Django 2.1.7 on 2019-07-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190701_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiries',
            name='date',
        ),
        migrations.RemoveField(
            model_name='enquiries',
            name='phoneno',
        ),
    ]
