# Generated by Django 2.1.7 on 2019-07-01 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190701_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiries',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiries',
            name='phoneno',
            field=models.CharField(default=datetime.datetime(2019, 7, 1, 11, 28, 30, 636721, tzinfo=utc), max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
