# Generated by Django 2.1.7 on 2019-05-02 11:12

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('short_description', models.CharField(max_length=50, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(null=True, upload_to=products.models.upload_image_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], max_length=50)),
            ],
        ),
    ]
