# Generated by Django 2.1.7 on 2019-07-07 05:29

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], max_length=50)),
                ('homefeatured', models.BooleanField(default=False)),
                ('productsfeatured', models.BooleanField(default=False)),
                ('enabledetail', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, unique=True)),
                ('short_description', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to=products.models.upload_image_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='childproduct',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childproduct', to='products.Product'),
        ),
    ]
