# Generated by Django 2.1.7 on 2019-05-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190502_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
