# Generated by Django 2.1.7 on 2019-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190626_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('child', 'Child')], max_length=50),
        ),
    ]
