# Generated by Django 2.1.7 on 2019-06-27 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190626_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childproduct',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentproduct', to='products.Product'),
        ),
    ]
