# Generated by Django 2.1.7 on 2019-06-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190627_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childproduct',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.Product'),
        ),
    ]
