# Generated by Django 2.1.7 on 2019-06-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190627_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='childproduct',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='childproduct',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childproduct', to='products.Product'),
        ),
    ]
