# Generated by Django 2.1.7 on 2019-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_childproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='childproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
