# Generated by Django 2.1.7 on 2019-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_childproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
