# Generated by Django 2.1.7 on 2019-06-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20190627_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.AddField(
            model_name='childproduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
