# Generated by Django 2.1.7 on 2019-06-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20190628_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='childproduct',
            name='hover',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], default='True', max_length=50),
            preserve_default=False,
        ),
    ]
