# Generated by Django 2.1.7 on 2019-06-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_childproduct_hover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childproduct',
            name='hover',
        ),
        migrations.AddField(
            model_name='product',
            name='hover',
            field=models.CharField(choices=[('active', 'Active'), ('in-active', 'In-active')], default='in-active', max_length=50),
            preserve_default=False,
        ),
    ]
