# Generated by Django 2.1.7 on 2019-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hover',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
