# Generated by Django 2.1.7 on 2019-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20190628_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childproduct',
            old_name='featured',
            new_name='homefeatured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hover',
        ),
        migrations.AddField(
            model_name='childproduct',
            name='enabledetailview',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='childproduct',
            name='productsfeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
