# Generated by Django 2.1.7 on 2019-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20190702_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='childproduct',
            name='enabledetail',
            field=models.BooleanField(default=False),
        ),
    ]
