# Generated by Django 2.1.7 on 2019-07-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_childproduct_enabledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
